---
- name: deploy cuda-vector-add pod
  k8s_v1_pod:
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    state: present
    restart_policy: OnFailure
    labels:
      app: "{{ application_name }}"
      namespace: "{{ namespace }}"
    containers:
      - name: "{{ application_name }}"
        image: "{{ container_image_name }}"
        env:
          - name: NVIDIA_VISIBLE_DEVICES
            value: all
          - name: NVIDIA_DRIVER_CAPABILITIES
            value: "compute,utility"
          - name: NVIDIA_REQUIRE_CUDA
            value: "cuda>=8.0"
        resources:
          limits:
            nvidia.com/gpu: 1 # requesting 1 GPU