- name: deploy
  hosts: localhost
  gather_facts: false
  connection: local

  roles:
    - oatakan.openshift-add-auth-config
    - role: ansible.kubernetes-modules
      install_python_requirements: no
    - role: ansibleplaybookbundle.asb-modules

  post_tasks:
    - name: create project from namespace
      k8s:
        name: '{{ namespace }}'
        api_version: v1
        kind: Project
        verify_ssl: no
        api_key: "{{ api_key }}"
        state: present
      environment:
        K8S_AUTH_KUBECONFIG: 'config'


    - name: deploy apb
      include_role:
        name: cuda-vector-add
      vars:
        action: provision
        playbook_debug: false