- name: set up authentication and project
  hosts: localhost
  gather_facts: false
  connection: local

  roles:
    - oatakan.openshift-add-auth-config
    - role: ansible-kubernetes-modules
      install_python_requirements: no

  post_tasks:
    - name: create project from namespace
      openshift_v1_project:
        name: '{{ namespace }}'
      environment:
        K8S_AUTH_KUBECONFIG: 'config'

- import_playbook: playbooks/provision.yml