- name: undeploy
  hosts: localhost
  gather_facts: false
  connection: local
  become: no

  pre_tasks:
    - name: authenticate with cluster
      include_role:
        name: oatakan.openshift-add-auth-config
      vars:
        oc_auth_type: api

  roles:
    - role: cuda-vector-add-apb
      apb_action: deprovision

  post_tasks:
    - name: delete project
      k8s:
        name: '{{ namespace }}'
        api_version: project.openshift.io/v1
        kind: Project
        validate_certs: no
        api_key: "{{ api_key }}"
        state: absent