- name: set up authentication and project
  hosts: localhost
  gather_facts: false
  connection: local

  roles:
    - oatakan.openshift-add-auth-config
    - role: ansible.kubernetes-modules
      install_python_requirements: no
    - role: ansibleplaybookbundle.asb-modules

  post_tasks:
    - name: undeploy apbs
      include_role:
        name: cuda-vector-add
      vars:
        action: deprovision
        playbook_debug: false

    - name: delete project
      openshift_raw:
        api_version: v1
        kind: Project
        name: '{{ namespace }}'
        state: absent
      environment:
        K8S_AUTH_KUBECONFIG: 'config'