---

apiVersion: v1
kind: Pod
metadata:
  name: {{ app_name }}
  namespace: {{ namespace }}
  labels:
    app: {{ app_name }}
    service: {{ app_name }}
spec:
  containers:
    - name: {{ app_name }}
      image: {{ container_image_name }}
      env:
        - name: NVIDIA_VISIBLE_DEVICES
          value: all
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: "compute,utility"
        - name: NVIDIA_REQUIRE_CUDA
          value: "cuda>=8.0"
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 1 GPU
  restartPolicy: OnFailure